#!/bin/bash
# Sway keybinding cheatsheet — displayed via rofi, Esc to close

bindings=(
    "── BASICS ───────────────────────────────────────"
    "Super+Return          Terminal"
    "Super+q               Browser"
    "Super+a               GUI editor"
    "Super+d               Run command (rofi)"
    "Super+w               Application menu (rofi drun)"
    "Super+Shift+c         Close window"
    "Super+Ctrl+r          Reload sway config"
    "Super+Shift+q         Exit sway"
    "Alt+Ctrl+l            Lock screen"
    "Ctrl+Print            Screenshot region → ~/Pictures/screenshots/"
    "Shift+Print           Screenshot region → clipboard"
    ""
    "── FOCUS ────────────────────────────────────────"
    "Super+h/j/k/l         Focus left/down/up/right"
    "Super+Left/Right      Prev/next workspace (both screens)"
    "Alt+j / Alt+k         Focus prev/next window"
    "Alt+Tab / Super+Tab   Focus next window"
    "Super+Ctrl+j/k        Focus prev/next screen"
    "Super+u               Focus urgent window"
    "Super+space           Toggle tiling/floating focus"
    "Super+Escape          Previous workspace"
    ""
    "── MOVE WINDOW ──────────────────────────────────"
    "Super+Shift+h/j/k/l   Swap in grid (screen 1) / Move (screen 2)"
    "Super+o               Move to other screen"
    "Super+Shift+o         Sync screen 2 to paired workspace of screen 1"
    "Super+Shift+1..9      Move to workspace N"
    "Ctrl+Shift+Super+1..9 Send to workspace N (screen-aware)"
    ""
    "── LAYOUT ───────────────────────────────────────"
    "Super+f               Fullscreen"
    "Super+m               Fullscreen"
    "Super+b               Split horizontal"
    "Super+Shift+v         Split vertical"
    "Super+Ctrl+space      Toggle floating"
    "Super+t               Sticky (always on top)"
    "Super+Shift+b         Toggle bar visibility"
    "Super+r               Resize mode  (h/j/k/l, Esc to exit)"
    ""
    "── WORKSPACES ───────────────────────────────────"
    "Super+1..9            Go to workspace"
    "Super+KP 1..9         Go to workspace (numpad)"
    ""
    "── SCRATCHPAD ───────────────────────────────────"
    "Super+n / Super+Shift+z / Super+Shift+-   Send to scratchpad"
    "Super+z / Super+-         Cycle scratchpad"
    ""
    "── VOLUME ───────────────────────────────────────"
    "Alt+Up/Down           Volume +1% / -1%"
    "XF86AudioRaise/Lower  Volume +5% / -5%"
    "Alt+m / XF86Mute      Mute toggle"
    "Alt+Ctrl+m            Volume 100%"
    "Alt+Ctrl+0            Volume 0%"
    ""
    "── BRIGHTNESS ───────────────────────────────────"
    "XF86MonBrightnessUp/Down  Brightness +10% / -10%"
    ""
    "── MEDIA (MPD) ──────────────────────────────────"
    "Alt+Ctrl+Up           Play/pause"
    "Alt+Ctrl+Down         Stop"
    "Alt+Ctrl+Left/Right   Prev / Next track"
    ""
    "── MISC ─────────────────────────────────────────"
    "Super+Ctrl+v          Switch to VM (workspace 20, only if VM running)"
    "Super+Shift+r         Restart Chrome (restores windows to workspaces)"
    "Alt+c                 Calendar (3 months)"
    "Super+c / Super+v     Sync clipboards (primary <-> regular)"
    "Super+Ctrl+p          Restart file picker (XDG portal)"
    "Super+s               This help"
)

printf '%s\n' "${bindings[@]}" | rofi \
    -dmenu \
    -p "Key Bindings" \
    -no-custom \
    -theme-str 'window { width: 58%; } listview { lines: 35; scrollbar: false; }' \
    2>/dev/null

exit 0
